
services:
  angular-app:
    build:
      context: .
    container_name: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
